/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f1xx.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void GPIO_Config (void);
void ClockInit();
void TIM2Init();
void delay();

int main(void)
{
	SystemInit();
	GPIO_Config();
	ClockInit();
	TIM2Init();

	/* Loop forever */
	for(;;)
	{
		uint8_t cur_state = (GPIOB->IDR & (1 << 1)); // read current state of PB1

		if(!cur_state) // if button is pushed
		{
			GPIOB->ODR |= (1 << 12);
			delay();
			GPIOB->ODR |= (1 << 13);
		}
	}
}

void GPIO_Config (void)
{
	// Set IOPB EN
	RCC->APB2ENR |= (1 << 3); // Enable GPIOB clock

	GPIOB->CRH |= (1 << 16) | (1 << 20);
	GPIOB->CRH &= ~((1 << 17) | (1 << 21));

	GPIOB->CRH &= ~((0b11 << 18) | (0b11 << 22));

	//
	// Set MODE1[1:0] = 00: : Input mode
	GPIOB->CRL &= ~(0b11 << 4); // clear bit 4 and 5

	// Clear  CNF1[1:0] = 01: Input floating
	GPIOB->CRL |= (0b11 << 6); // Set bit 6
	GPIOB->CRL &= ~(0b11 << 7); // Clear bit 7
}

void ClockInit(){
	// Bit 4 PRFTBE: Prefetch buffer enable
	FLASH->ACR |= (1 << 4); // Prefetch is enabled

	//
	// HSE Configuration
	// Bit 16 HSEON: HSE clock enable
	RCC->CR |= (1 << 16); // HSE oscillator ON

	/* Wait till HSE is ready */
	// Bit 17 HSERDY: External high-speed clock ready flag
	while(!(RCC->CR & (1 << 17)));

	//
	// PLL Configuration
	/* Disable the main PLL. */
	// Bit 24 PLLON: PLL enable
	RCC->CR &= ~(1 << 24); // PLL OFF

	/* Wait till PLL is disabled */
	// Bit 25 PLLRDY: PLL clock ready flag
	while(RCC->CR & (1 << 25));

	/* Set PREDIV1 Value */
	// Bit 17 PLLXTPRE: HSE divider for PLL entry
	RCC->CFGR &= ~(1 << 17); // HSE clock not divided

	/* Configure the main PLL clock source and multiplication factors. */
	// Bit 16 PLLSRC: PLL entry clock source
	RCC->CFGR |= (1 << 16); // HSE oscillator clock selected as PLL input clock
	// Bits 21:18 PLLMUL: PLL multiplication factor
	RCC->CFGR &= ~(0b1111 << 18);
	RCC->CFGR |= (0b111 << 18); // PLL input clock x 9

	/* Enable the main PLL. */
	// Bit 24 PLLON: PLL enable
	RCC->CR |= (1 << 24); // PLL ON

	/* Wait till PLL is ready */
	// Bit 25 PLLRDY: PLL clock ready flag
	while(!(RCC->CR & (1 << 25)));

	// Bits 2:0 LATENCY: Latency
	FLASH->ACR &= (0b111 << 0);
	FLASH->ACR |= (0b10 << 0); // Two wait states, if 48 MHz < SYSCLK <= 72 MHz

	// HCLK Configuration
	/* Set the highest APBx dividers in order to ensure that we do not go through
         5     a non-spec phase whatever we decrease or increase HCLK. */
	// Bits 10:8 PPRE1: APB low-speed prescaler (APB1)
	RCC->CFGR |= (0b111 << 8); // HCLK divided by 16
	// Bits 13:11 PPRE2: APB high-speed prescaler (APB2)
	RCC->CFGR |= (0b111 << 11); // HCLK divided by 16

	/* Set the new HCLK clock divider */
	// Bits 7:4 HPRE: AHB prescaler
	RCC->CFGR &= ~(0b1111 << 4); // SYSCLK not divided

	//
	// SYSCLK Configuration
	/* PLL is selected as System Clock Source */
	// Bit 25 PLLRDY: PLL clock ready flag
	/* Check the PLL ready flag */
	while(!(RCC->CR & (1 << 25)));

	// Bits 1:0 SW: System clock switch
	RCC->CFGR &= ~(1 << 0); // PLL selected as system clock
	RCC->CFGR |= (1 << 1);

	while( ( ( RCC->CFGR & (0b11 << 2) ) >> 2 ) != (0b10) ); // Bits 3:2 SWS: System clock switch status

	//
	// PCLK1 Configuration
	// Bits 10:8 PPRE1: APB low-speed prescaler (APB1)
	RCC->CFGR &= ~(0b111 << 8);
	RCC->CFGR |= (0b100 << 8); // HCLK divided by 2

	// PCLK2 Configuration
	// Bits 13:11 PPRE2: APB high-speed prescaler (APB2)
	RCC->CFGR &= ~(0b111 << 11); // HCLK not divided
}

void TIM2Init()
{
	// Bit 0 TIM2EN: TIM2 timer clock enable
	RCC->APB1ENR |= (1 << 0); // TIM2 clock enabled

	// Bits 15:0 PSC[15:0]: Prescaler value
	TIM2->PSC = 7200 - 1;

	// Bits 15:0 ARR[15:0]: Auto-reload value
	TIM2->ARR = 20000;

	// Bug?
	delay();
}

void delay()
{
	// Clear Update interrupt flag
	TIM2->SR = 0;

	// Bit 0 CEN: Counter enable
	TIM2->CR1 |= (1 << 0); // Counter enabled

	// Bit 0 UIF: Update interrupt flag
	while(!(TIM2->SR & (1 << 0)));

	TIM2->CR1 &= ~(1 << 0); // Counter disabled
}
